
import { House, Client, CheckInType } from './types';

export const ADMIN_PASSWORD = 'admin';

// Helper to create beds
const createBeds = (count: number, startNum: number = 1) => 
  Array.from({ length: count }, (_, i) => ({
    id: `b-${Math.random().toString(36).substr(2, 9)}`,
    number: `${startNum + i}`,
    occupantId: null
  }));

export const MOCK_HOUSES: House[] = [
  {
    id: 'h_elberta',
    name: 'Elberta House',
    address: '319 Elberta St. Nashville, TN 37210',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop',
    rooms: Array.from({ length: 7 }, (_, i) => ({
      id: `r-elberta-${i+1}`,
      name: `Room ${i+1}`,
      beds: createBeds(2, 1) // 2 beds per room
    }))
  },
  {
    id: 'h_thunderbird',
    name: 'Thunderbird House',
    address: '6536 Thunderbird Dr. Nashville, TN 37209',
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop',
    rooms: [
      { id: 'r-tb-1', name: 'Room 1', beds: createBeds(1, 1) },
      { id: 'r-tb-2', name: 'Room 2', beds: createBeds(1, 1) },
      { id: 'r-tb-3', name: 'Room 3', beds: createBeds(4, 1) },
      { id: 'r-tb-4', name: 'Room 4', beds: createBeds(2, 1) },
      { id: 'r-tb-5', name: 'Room 5', beds: createBeds(2, 1) },
      { id: 'r-tb-6', name: 'Room 6', beds: createBeds(3, 1) }
    ]
  }
];

export const MOCK_CLIENTS: Client[] = [
  // Elberta House Residents (10 residents)
  {
    id: 'c1',
    targetHouseId: 'h_elberta',
    firstName: 'Michael',
    lastName: 'Thompson',
    age: '28',
    dob: '1996-03-12',
    phone: '615-555-0101',
    email: 'michael.t@example.com',
    dlNumber: 'TN9876543',
    dlState: 'TN',
    dlExpiration: '2026-03-12',
    emergencyName: 'Sarah Thompson',
    emergencyPhone: '615-555-0102',
    emergencyAddress: '123 Oak St, Nashville, TN',
    doctorName: 'Dr. Emily Carter',
    doctorPhone: '615-555-9001',
    doctorAddress: 'Vanderbilt Medical Center',
    allergies: 'None',
    hasOverdosed: true,
    overdoseCount: '1',
    overdoseDates: '2022',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Drug Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Motivated to stay sober.',
    medications: [{ name: 'Naltrexone', dose: '50mg daily', doctor: 'Dr. Carter', contact: '615-555-9001', reason: 'Opioid dependence' }],
    agreementCommunity: true,
    signatureCommunity: 'Michael Thompson',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Michael Thompson',
    soberDate: '2024-06-15',
    submissionDate: '2024-06-20',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c2',
    targetHouseId: 'h_elberta',
    firstName: 'David',
    lastName: 'Martinez',
    age: '35',
    dob: '1989-08-22',
    phone: '615-555-0103',
    email: 'david.m@example.com',
    dlNumber: 'TN8765432',
    dlState: 'TN',
    dlExpiration: '2025-08-22',
    emergencyName: 'Maria Martinez',
    emergencyPhone: '615-555-0104',
    emergencyAddress: '456 Elm St, Nashville, TN',
    doctorName: 'Dr. James Wilson',
    doctorPhone: '615-555-9002',
    doctorAddress: 'Nashville General',
    allergies: 'Penicillin',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: true,
    felonyExplanation: 'Possession with intent, 2018',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: true,
    paroleExplanation: 'Parole until 2026',
    paroleOfficerName: 'Officer Davis',
    paroleOfficerPhone: '615-555-7001',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Good progress in recovery.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'David Martinez',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'David Martinez',
    soberDate: '2024-03-10',
    submissionDate: '2024-03-15',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c3',
    targetHouseId: 'h_elberta',
    firstName: 'Robert',
    lastName: 'Johnson',
    age: '42',
    dob: '1982-11-05',
    phone: '615-555-0105',
    email: 'robert.j@example.com',
    dlNumber: 'TN7654321',
    dlState: 'TN',
    dlExpiration: '2026-11-05',
    emergencyName: 'Linda Johnson',
    emergencyPhone: '615-555-0106',
    emergencyAddress: '789 Maple Ave, Nashville, TN',
    doctorName: 'Dr. Susan Lee',
    doctorPhone: '615-555-9003',
    doctorAddress: 'St. Thomas Hospital',
    allergies: 'Sulfa drugs',
    hasOverdosed: true,
    overdoseCount: '3',
    overdoseDates: '2019, 2020, 2022',
    hasAttemptedSuicide: true,
    suicideCount: '1',
    suicideDates: '2021',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Mental Health Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Working through trauma with counselor.',
    medications: [
      { name: 'Suboxone', dose: '8mg/2mg daily', doctor: 'Dr. Lee', contact: '615-555-9003', reason: 'Opioid maintenance' },
      { name: 'Zoloft', dose: '100mg daily', doctor: 'Dr. Lee', contact: '615-555-9003', reason: 'Depression' }
    ],
    agreementCommunity: true,
    signatureCommunity: 'Robert Johnson',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Robert Johnson',
    soberDate: '2024-01-20',
    submissionDate: '2024-01-25',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c4',
    targetHouseId: 'h_elberta',
    firstName: 'Christopher',
    lastName: 'Williams',
    age: '31',
    dob: '1993-02-18',
    phone: '615-555-0107',
    email: 'chris.w@example.com',
    dlNumber: 'TN6543210',
    dlState: 'TN',
    dlExpiration: '2025-02-18',
    emergencyName: 'Patricia Williams',
    emergencyPhone: '615-555-0108',
    emergencyAddress: '321 Pine St, Nashville, TN',
    doctorName: 'Dr. Michael Chang',
    doctorPhone: '615-555-9004',
    doctorAddress: 'TriStar Medical',
    allergies: 'Latex',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Self-referred, very committed.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Christopher Williams',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Christopher Williams',
    soberDate: '2024-09-01',
    submissionDate: '2024-09-05',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c5',
    targetHouseId: 'h_elberta',
    firstName: 'James',
    lastName: 'Anderson',
    age: '26',
    dob: '1998-07-30',
    phone: '615-555-0109',
    email: 'james.a@example.com',
    dlNumber: 'TN5432109',
    dlState: 'TN',
    dlExpiration: '2027-07-30',
    emergencyName: 'Betty Anderson',
    emergencyPhone: '615-555-0110',
    emergencyAddress: '654 Cedar Ln, Nashville, TN',
    doctorName: 'Dr. Rachel Green',
    doctorPhone: '615-555-9005',
    doctorAddress: 'Summit Medical',
    allergies: 'None',
    hasOverdosed: true,
    overdoseCount: '2',
    overdoseDates: '2023',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: true,
    assaultExplanation: 'Bar fight, misdemeanor 2022',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Young and eager to change.',
    medications: [{ name: 'Vivitrol', dose: 'Monthly injection', doctor: 'Dr. Green', contact: '615-555-9005', reason: 'Alcohol dependence' }],
    agreementCommunity: true,
    signatureCommunity: 'James Anderson',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'James Anderson',
    soberDate: '2024-08-12',
    submissionDate: '2024-08-15',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c6',
    targetHouseId: 'h_elberta',
    firstName: 'Daniel',
    lastName: 'Brown',
    age: '39',
    dob: '1985-04-25',
    phone: '615-555-0111',
    email: 'daniel.b@example.com',
    dlNumber: 'TN4321098',
    dlState: 'TN',
    dlExpiration: '2025-04-25',
    emergencyName: 'Karen Brown',
    emergencyPhone: '615-555-0112',
    emergencyAddress: '987 Birch Rd, Nashville, TN',
    doctorName: 'Dr. Andrew Kim',
    doctorPhone: '615-555-9006',
    doctorAddress: 'Centennial Medical',
    allergies: 'Shellfish',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: true,
    felonyExplanation: 'Drug trafficking, 2015',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: true,
    paroleExplanation: 'Parole until 2027',
    paroleOfficerName: 'Officer Martinez',
    paroleOfficerPhone: '615-555-7002',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Completed 90 days, very stable.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Daniel Brown',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Daniel Brown',
    soberDate: '2024-04-01',
    submissionDate: '2024-04-05',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c7',
    targetHouseId: 'h_elberta',
    firstName: 'Thomas',
    lastName: 'Davis',
    age: '44',
    dob: '1980-09-14',
    phone: '615-555-0113',
    email: 'thomas.d@example.com',
    dlNumber: 'TN3210987',
    dlState: 'TN',
    dlExpiration: '2026-09-14',
    emergencyName: 'Nancy Davis',
    emergencyPhone: '615-555-0114',
    emergencyAddress: '159 Willow Way, Nashville, TN',
    doctorName: 'Dr. Lisa Morgan',
    doctorPhone: '615-555-9007',
    doctorAddress: 'Baptist Hospital',
    allergies: 'Aspirin',
    hasOverdosed: true,
    overdoseCount: '1',
    overdoseDates: '2020',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Veterans Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Army veteran, PTSD treatment ongoing.',
    medications: [
      { name: 'Prazosin', dose: '5mg nightly', doctor: 'Dr. Morgan', contact: '615-555-9007', reason: 'PTSD nightmares' },
      { name: 'Sertraline', dose: '150mg daily', doctor: 'Dr. Morgan', contact: '615-555-9007', reason: 'PTSD/Depression' }
    ],
    agreementCommunity: true,
    signatureCommunity: 'Thomas Davis',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Thomas Davis',
    soberDate: '2024-05-20',
    submissionDate: '2024-05-25',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c8',
    targetHouseId: 'h_elberta',
    firstName: 'Joseph',
    lastName: 'Miller',
    age: '29',
    dob: '1995-12-08',
    phone: '615-555-0115',
    email: 'joseph.m@example.com',
    dlNumber: 'TN2109876',
    dlState: 'TN',
    dlExpiration: '2025-12-08',
    emergencyName: 'Helen Miller',
    emergencyPhone: '615-555-0116',
    emergencyAddress: '753 Spruce St, Nashville, TN',
    doctorName: 'Dr. Kevin Park',
    doctorPhone: '615-555-9008',
    doctorAddress: 'Community Health Center',
    allergies: 'None',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Family support strong.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Joseph Miller',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Joseph Miller',
    soberDate: '2024-10-03',
    submissionDate: '2024-10-05',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c9',
    targetHouseId: 'h_elberta',
    firstName: 'Matthew',
    lastName: 'Wilson',
    age: '37',
    dob: '1987-06-19',
    phone: '615-555-0117',
    email: 'matthew.w@example.com',
    dlNumber: 'TN1098765',
    dlState: 'TN',
    dlExpiration: '2026-06-19',
    emergencyName: 'Susan Wilson',
    emergencyPhone: '615-555-0118',
    emergencyAddress: '951 Poplar Ave, Nashville, TN',
    doctorName: 'Dr. Jennifer Ross',
    doctorPhone: '615-555-9009',
    doctorAddress: 'Metro General Hospital',
    allergies: 'Codeine',
    hasOverdosed: true,
    overdoseCount: '2',
    overdoseDates: '2021, 2023',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Drug Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Working full-time, great attitude.',
    medications: [{ name: 'Buprenorphine', dose: '16mg daily', doctor: 'Dr. Ross', contact: '615-555-9009', reason: 'Opioid maintenance' }],
    agreementCommunity: true,
    signatureCommunity: 'Matthew Wilson',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Matthew Wilson',
    soberDate: '2024-02-14',
    submissionDate: '2024-02-18',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c10',
    targetHouseId: 'h_elberta',
    firstName: 'Anthony',
    lastName: 'Moore',
    age: '33',
    dob: '1991-10-27',
    phone: '615-555-0119',
    email: 'anthony.m@example.com',
    dlNumber: 'TN0987654',
    dlState: 'TN',
    dlExpiration: '2025-10-27',
    emergencyName: 'Dorothy Moore',
    emergencyPhone: '615-555-0120',
    emergencyAddress: '357 Hickory Dr, Nashville, TN',
    doctorName: 'Dr. Brian Foster',
    doctorPhone: '615-555-9010',
    doctorAddress: 'Skyline Medical',
    allergies: 'None',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Sponsor active in AA.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Anthony Moore',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Anthony Moore',
    soberDate: '2024-07-22',
    submissionDate: '2024-07-25',
    status: 'active',
    assignedHouseId: 'h_elberta',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },

  // Thunderbird House Residents (10 residents)
  {
    id: 'c11',
    targetHouseId: 'h_thunderbird',
    firstName: 'Brandon',
    lastName: 'Taylor',
    age: '30',
    dob: '1994-01-15',
    phone: '615-555-0201',
    email: 'brandon.t@example.com',
    dlNumber: 'TN9876540',
    dlState: 'TN',
    dlExpiration: '2026-01-15',
    emergencyName: 'Michelle Taylor',
    emergencyPhone: '615-555-0202',
    emergencyAddress: '100 River Rd, Nashville, TN',
    doctorName: 'Dr. Sarah White',
    doctorPhone: '615-555-9011',
    doctorAddress: 'Ascension Medical',
    allergies: 'Iodine',
    hasOverdosed: true,
    overdoseCount: '1',
    overdoseDates: '2023',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Drug Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Doing well, attending meetings regularly.',
    medications: [{ name: 'Naltrexone', dose: '50mg daily', doctor: 'Dr. White', contact: '615-555-9011', reason: 'Alcohol dependence' }],
    agreementCommunity: true,
    signatureCommunity: 'Brandon Taylor',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Brandon Taylor',
    soberDate: '2024-04-10',
    submissionDate: '2024-04-12',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c12',
    targetHouseId: 'h_thunderbird',
    firstName: 'Kevin',
    lastName: 'Garcia',
    age: '27',
    dob: '1997-05-03',
    phone: '615-555-0203',
    email: 'kevin.g@example.com',
    dlNumber: 'TN8765430',
    dlState: 'TN',
    dlExpiration: '2028-05-03',
    emergencyName: 'Rosa Garcia',
    emergencyPhone: '615-555-0204',
    emergencyAddress: '200 Valley View, Nashville, TN',
    doctorName: 'Dr. Carlos Rivera',
    doctorPhone: '615-555-9012',
    doctorAddress: 'Southern Hills Medical',
    allergies: 'None',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: true,
    felonyExplanation: 'Burglary, 2019',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: true,
    paroleExplanation: 'Parole until 2025',
    paroleOfficerName: 'Officer Thompson',
    paroleOfficerPhone: '615-555-7003',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Excellent peer support.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Kevin Garcia',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Kevin Garcia',
    soberDate: '2024-06-28',
    submissionDate: '2024-07-01',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c13',
    targetHouseId: 'h_thunderbird',
    firstName: 'Brian',
    lastName: 'Rodriguez',
    age: '41',
    dob: '1983-08-16',
    phone: '615-555-0205',
    email: 'brian.r@example.com',
    dlNumber: 'TN7654320',
    dlState: 'TN',
    dlExpiration: '2025-08-16',
    emergencyName: 'Angela Rodriguez',
    emergencyPhone: '615-555-0206',
    emergencyAddress: '300 Summit Dr, Nashville, TN',
    doctorName: 'Dr. Patricia Hall',
    doctorPhone: '615-555-9013',
    doctorAddress: 'Gateway Medical',
    allergies: 'Morphine',
    hasOverdosed: true,
    overdoseCount: '4',
    overdoseDates: '2018, 2019, 2021, 2022',
    hasAttemptedSuicide: true,
    suicideCount: '2',
    suicideDates: '2020, 2022',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Mental Health Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'High risk but showing improvement.',
    medications: [
      { name: 'Suboxone', dose: '16mg/4mg daily', doctor: 'Dr. Hall', contact: '615-555-9013', reason: 'Opioid maintenance' },
      { name: 'Lithium', dose: '900mg daily', doctor: 'Dr. Hall', contact: '615-555-9013', reason: 'Bipolar disorder' },
      { name: 'Risperidone', dose: '2mg nightly', doctor: 'Dr. Hall', contact: '615-555-9013', reason: 'Mood stabilization' }
    ],
    agreementCommunity: true,
    signatureCommunity: 'Brian Rodriguez',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Brian Rodriguez',
    soberDate: '2024-01-05',
    submissionDate: '2024-01-08',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c14',
    targetHouseId: 'h_thunderbird',
    firstName: 'Eric',
    lastName: 'Hernandez',
    age: '34',
    dob: '1990-03-22',
    phone: '615-555-0207',
    email: 'eric.h@example.com',
    dlNumber: 'TN6543200',
    dlState: 'TN',
    dlExpiration: '2026-03-22',
    emergencyName: 'Carmen Hernandez',
    emergencyPhone: '615-555-0208',
    emergencyAddress: '400 Park Pl, Nashville, TN',
    doctorName: 'Dr. Mark Stevens',
    doctorPhone: '615-555-9014',
    doctorAddress: 'Horizon Health',
    allergies: 'None',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Self-motivated, good communicator.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Eric Hernandez',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Eric Hernandez',
    soberDate: '2024-09-15',
    submissionDate: '2024-09-18',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c15',
    targetHouseId: 'h_thunderbird',
    firstName: 'Gregory',
    lastName: 'Lopez',
    age: '36',
    dob: '1988-11-11',
    phone: '615-555-0209',
    email: 'gregory.l@example.com',
    dlNumber: 'TN5432100',
    dlState: 'TN',
    dlExpiration: '2025-11-11',
    emergencyName: 'Julia Lopez',
    emergencyPhone: '615-555-0210',
    emergencyAddress: '500 Forest Ave, Nashville, TN',
    doctorName: 'Dr. Amanda Clark',
    doctorPhone: '615-555-9015',
    doctorAddress: 'Liberty Medical',
    allergies: 'Bee stings',
    hasOverdosed: true,
    overdoseCount: '1',
    overdoseDates: '2021',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: true,
    felonyExplanation: 'Possession, 2020',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Drug Court',
    onParoleProbation: true,
    paroleExplanation: 'Parole until 2026',
    paroleOfficerName: 'Officer Garcia',
    paroleOfficerPhone: '615-555-7004',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Making steady progress.',
    medications: [{ name: 'Vivitrol', dose: 'Monthly injection', doctor: 'Dr. Clark', contact: '615-555-9015', reason: 'Alcohol/opioid dependence' }],
    agreementCommunity: true,
    signatureCommunity: 'Gregory Lopez',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Gregory Lopez',
    soberDate: '2024-05-07',
    submissionDate: '2024-05-10',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c16',
    targetHouseId: 'h_thunderbird',
    firstName: 'Joshua',
    lastName: 'Lee',
    age: '25',
    dob: '1999-02-28',
    phone: '615-555-0211',
    email: 'joshua.l@example.com',
    dlNumber: 'TN4321000',
    dlState: 'TN',
    dlExpiration: '2027-02-28',
    emergencyName: 'Grace Lee',
    emergencyPhone: '615-555-0212',
    emergencyAddress: '600 Lake Dr, Nashville, TN',
    doctorName: 'Dr. Daniel Wright',
    doctorPhone: '615-555-9016',
    doctorAddress: 'Unity Health',
    allergies: 'None',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Youngest resident, very determined.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Joshua Lee',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Joshua Lee',
    soberDate: '2024-10-20',
    submissionDate: '2024-10-22',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c17',
    targetHouseId: 'h_thunderbird',
    firstName: 'Kenneth',
    lastName: 'Walker',
    age: '38',
    dob: '1986-07-07',
    phone: '615-555-0213',
    email: 'kenneth.w@example.com',
    dlNumber: 'TN3210900',
    dlState: 'TN',
    dlExpiration: '2026-07-07',
    emergencyName: 'Deborah Walker',
    emergencyPhone: '615-555-0214',
    emergencyAddress: '700 Mountain View, Nashville, TN',
    doctorName: 'Dr. Robert Young',
    doctorPhone: '615-555-9017',
    doctorAddress: 'Premier Medical',
    allergies: 'Pollen',
    hasOverdosed: true,
    overdoseCount: '2',
    overdoseDates: '2020, 2022',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: true,
    assaultExplanation: 'Domestic dispute, 2019',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Working on anger management.',
    medications: [
      { name: 'Methadone', dose: '80mg daily', doctor: 'Dr. Young', contact: '615-555-9017', reason: 'Opioid maintenance' },
      { name: 'Buspirone', dose: '15mg twice daily', doctor: 'Dr. Young', contact: '615-555-9017', reason: 'Anxiety' }
    ],
    agreementCommunity: true,
    signatureCommunity: 'Kenneth Walker',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Kenneth Walker',
    soberDate: '2024-03-18',
    submissionDate: '2024-03-20',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c18',
    targetHouseId: 'h_thunderbird',
    firstName: 'Steven',
    lastName: 'Hall',
    age: '32',
    dob: '1992-09-25',
    phone: '615-555-0215',
    email: 'steven.h@example.com',
    dlNumber: 'TN2109800',
    dlState: 'TN',
    dlExpiration: '2025-09-25',
    emergencyName: 'Carol Hall',
    emergencyPhone: '615-555-0216',
    emergencyAddress: '800 Sunset Blvd, Nashville, TN',
    doctorName: 'Dr. Linda Martinez',
    doctorPhone: '615-555-9018',
    doctorAddress: 'Cornerstone Health',
    allergies: 'Contrast dye',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: false,
    specializedCourtName: '',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Strong family involvement.',
    medications: [],
    agreementCommunity: true,
    signatureCommunity: 'Steven Hall',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Steven Hall',
    soberDate: '2024-08-05',
    submissionDate: '2024-08-08',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c19',
    targetHouseId: 'h_thunderbird',
    firstName: 'Timothy',
    lastName: 'Allen',
    age: '40',
    dob: '1984-04-12',
    phone: '615-555-0217',
    email: 'timothy.a@example.com',
    dlNumber: 'TN1098700',
    dlState: 'TN',
    dlExpiration: '2026-04-12',
    emergencyName: 'Donna Allen',
    emergencyPhone: '615-555-0218',
    emergencyAddress: '900 Broadway, Nashville, TN',
    doctorName: 'Dr. Thomas Baker',
    doctorPhone: '615-555-9019',
    doctorAddress: 'Alliance Medical',
    allergies: 'Dairy',
    hasOverdosed: true,
    overdoseCount: '3',
    overdoseDates: '2019, 2021, 2023',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: true,
    felonyExplanation: 'Forgery, 2017',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Drug Court',
    onParoleProbation: true,
    paroleExplanation: 'Parole until 2028',
    paroleOfficerName: 'Officer Wilson',
    paroleOfficerPhone: '615-555-7005',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Multiple relapses but persistent.',
    medications: [{ name: 'Buprenorphine/Naloxone', dose: '12mg/3mg daily', doctor: 'Dr. Baker', contact: '615-555-9019', reason: 'Opioid maintenance' }],
    agreementCommunity: true,
    signatureCommunity: 'Timothy Allen',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Timothy Allen',
    soberDate: '2024-02-01',
    submissionDate: '2024-02-03',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  },
  {
    id: 'c20',
    targetHouseId: 'h_thunderbird',
    firstName: 'Ronald',
    lastName: 'Young',
    age: '43',
    dob: '1981-12-30',
    phone: '615-555-0219',
    email: 'ronald.y@example.com',
    dlNumber: 'TN0987600',
    dlState: 'TN',
    dlExpiration: '2025-12-30',
    emergencyName: 'Barbara Young',
    emergencyPhone: '615-555-0220',
    emergencyAddress: '1000 Church St, Nashville, TN',
    doctorName: 'Dr. Nancy Scott',
    doctorPhone: '615-555-9020',
    doctorAddress: 'Comprehensive Care',
    allergies: 'Gluten',
    hasOverdosed: false,
    overdoseCount: '',
    overdoseDates: '',
    hasAttemptedSuicide: false,
    suicideCount: '',
    suicideDates: '',
    hasFelony: false,
    felonyExplanation: '',
    isSexOffender: false,
    hasAssaultCharges: false,
    assaultExplanation: '',
    isSpecializedCourt: true,
    specializedCourtName: 'Veterans Court',
    onParoleProbation: false,
    paroleExplanation: '',
    paroleOfficerName: '',
    paroleOfficerPhone: '',
    hasPendingCharges: false,
    pendingChargesExplanation: '',
    comments: 'Navy veteran, strong leadership.',
    medications: [
      { name: 'Trazodone', dose: '100mg nightly', doctor: 'Dr. Scott', contact: '615-555-9020', reason: 'Insomnia' }
    ],
    agreementCommunity: true,
    signatureCommunity: 'Ronald Young',
    agreementLiability: true,
    agreementCovid: true,
    agreementProperty: true,
    signatureFinal: 'Ronald Young',
    soberDate: '2024-06-01',
    submissionDate: '2024-06-04',
    status: 'active',
    assignedHouseId: 'h_thunderbird',
    assignedBedId: null,
    checkInLogs: [],
    drugTestLogs: [],
    password: 'password'
  }
];